version: '3'
services:
  front-end:
    container_name: react-app
    restart: always
    build: myfrontendapp/
    ports:
      - '8000:3000'
  server-app:
    container_name: server-app
    restart: always
    build: myServerApp/
    ports:
      - '8080:3001'
    links:
      - mongo
      - redis
    environment:
      - REDIS_URL=redis: //cache
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  redis:
    container_name: cache
    image: redis
    expose:
      - 6379
  